---
dotfiles_repo: "https://github.com/chungimo/osx_dotfiles.git"
dotfiles_repo_accept_hostkey: no
dotfiles_repo_local_destination: "~/Documents/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .inputrc
  - .vimrc
